spring.application.name=stories
spring.profiles.active=dev

spring.jpa.hibernate.ddl-auto=create

jwt.secret=nMDszpZ_VV4rTk0g7pLR9DgBAeaWMaA5zQ-0t7Qc7LZgyrulYifl1wGYoMbpLh2RLjIxlQ
jwt.expiration=86400000